version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: "/.github/actions/frontend"
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: "/cli"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: "/sdk/go"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: "/cli/internal/webui/frontend"
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: "/sdk/python"
    schedule:
      interval: weekly
