# Generated by packaging/homebrew/render.sh — do not edit by hand.
# Reference copy. The live cask is published to matheus-meneses/homebrew-aide
# by the update-homebrew-tap release job with real version + checksum.
cask "aide" do
  version "0.0.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/matheus-meneses/aide/releases/download/v#{version}/Aide-#{version}.dmg"
  name "Aide"
  desc "Personal work assistant desktop app"
  homepage "https://github.com/matheus-meneses/aide"

  app "Aide.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Aide.app"],
                   sudo: false
  end

  caveats <<~CAVEATS
    Aide.app is not notarized by Apple. This cask removes the quarantine
    attribute on install so it launches normally. If macOS still blocks it,
    right-click the app and choose Open the first time.
  CAVEATS

  zap trash: [
    "~/.aide",
    "~/Library/Application Support/Aide",
  ]
end
