# Generated by packaging/homebrew/render.sh — do not edit by hand.
# Reference copy. The live formula is published to matheus-meneses/homebrew-aide
# by the update-homebrew-tap release job with real version + checksums.
class Aide < Formula
  desc "Personal work assistant CLI"
  homepage "https://github.com/matheus-meneses/aide"
  version "0.0.0"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "https://github.com/matheus-meneses/aide/releases/download/v0.0.0/aide_darwin_arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/matheus-meneses/aide/releases/download/v0.0.0/aide_darwin_amd64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/matheus-meneses/aide/releases/download/v0.0.0/aide_linux_arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/matheus-meneses/aide/releases/download/v0.0.0/aide_linux_amd64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install Dir["aide_*"].first => "aide"
    generate_completions_from_executable(bin/"aide", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aide version")
  end
end
