#!/usr/bin/env bash
set -euo pipefail

# Renders the aide Homebrew formula (CLI) and cask (desktop app) for a release.
#
# Usage: render.sh <version> <sums-dir> <out-dir>
#   <version>   release version without the leading "v" (e.g. 1.4.0)
#   <sums-dir>  directory containing "<asset>.sha256" files, where each file's
#               first field is the sha256 (output of sha256sum/shasum -a 256)
#   <out-dir>   destination; Formula/aide.rb and Casks/aide.rb are written here
#
# Expected checksum files in <sums-dir>:
#   aide_darwin_arm64.sha256  aide_darwin_amd64.sha256
#   aide_linux_arm64.sha256   aide_linux_amd64.sha256
#   Aide-<version>.dmg.sha256

if [[ $# -ne 3 ]]; then
  echo "usage: render.sh <version> <sums-dir> <out-dir>" >&2
  exit 2
fi

VERSION="$1"
SUMS="$2"
OUT="$3"
REPO="matheus-meneses/aide"
BASE="https://github.com/$REPO/releases/download/v$VERSION"

sha() {
  local file="$SUMS/$1.sha256"
  if [[ ! -f "$file" ]]; then
    echo "missing checksum: $file" >&2
    exit 1
  fi
  awk '{print $1; exit}' "$file"
}

mkdir -p "$OUT/Formula" "$OUT/Casks"

cat > "$OUT/Formula/aide.rb" <<EOF
# Generated by packaging/homebrew/render.sh — do not edit by hand.
class Aide < Formula
  desc "Personal work assistant CLI"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "$BASE/aide_darwin_arm64"
      sha256 "$(sha aide_darwin_arm64)"
    end
    on_intel do
      url "$BASE/aide_darwin_amd64"
      sha256 "$(sha aide_darwin_amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/aide_linux_arm64"
      sha256 "$(sha aide_linux_arm64)"
    end
    on_intel do
      url "$BASE/aide_linux_amd64"
      sha256 "$(sha aide_linux_amd64)"
    end
  end

  def install
    bin.install Dir["aide_*"].first => "aide"
    chmod 0555, bin/"aide"
    generate_completions_from_executable(bin/"aide", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aide version")
  end
end
EOF

cat > "$OUT/Casks/aide.rb" <<EOF
# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "aide" do
  version "$VERSION"
  sha256 "$(sha "Aide-$VERSION.dmg")"

  url "$BASE/Aide-#{version}.dmg"
  name "Aide"
  desc "Personal work assistant desktop app"
  homepage "https://github.com/$REPO"

  app "Aide.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Aide.app"],
                   sudo: false
  end

  caveats <<~CAVEATS
    Aide.app is not notarized by Apple. This cask removes the quarantine
    attribute on install so it launches normally. If macOS still blocks it,
    right-click the app and choose Open the first time.
  CAVEATS

  zap trash: [
    "~/.aide",
    "~/Library/Application Support/Aide",
  ]
end
EOF

echo "rendered $OUT/Formula/aide.rb and $OUT/Casks/aide.rb (v$VERSION)"
